title: MusicRNN
description: A recurrent neural network to generate music notes.
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  GitHub Repository: https://github.com/eyal-sasson/music-rnn
  Guided Notebook: https://example.com

search_enabled: false
