title: MusicRNN
description: A recurrent neural network to generate music notes.
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  GitHub Repository: https://github.com/eyal-sasson/music-rnn
  Guided Notebook: https://colab.research.google.com/github/eyal-sasson/music-rnn/blob/main/MusicRNN.ipynb

search_enabled: false

permalink:
  /:title

remote-theme: just-the-docs/just-the-docs
